# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, A, Gemini, exec, omarchy-launch-webapp "https://gemini.google.com/app"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# NOTE: Don't care about these!
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://gmail.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~ ~ ~ ~ ~ ~ FUN ~ ~ ~ ~ ~ START ~ ~ ~ ~ ~ NOW ~ ~ ~ ~ ~ ~
# ~~~~~~~~~~~~~~ Custom config and overrides ~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Move Horizontal -> vertical split reorient to Y
unbind = SUPER, Y
bindd = SUPER, Y, Toggle window split, togglesplit, # dwindle

# Rebind help to ?
unbind = SUPER SHIFT, SLASH
bindd = SUPER SHIFT, SLASH, Show key bindings, exec, omarchy-menu-keybindings

# Move focus with SUPER + hjkl
unbind = SUPER, H
bindd = SUPER, H, Move window focus left, movefocus, l

unbind = SUPER, L
bindd = SUPER, L, Move window focus right, movefocus, r

unbind = SUPER, K
bindd = SUPER, K, Move window focus up, movefocus, u

unbind = SUPER, J
bindd = SUPER, J, Move window focus down, movefocus, d

# Remove previous bind for move to silent
unbind = SUPER ALT, S
unbind = SUPER SHIFT, S
bindd = SUPER SHIFT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad
