theme = "kanagawa"

[editor]
scrolloff = 10 # default 5
cursorline = true
completion-timeout = 250 # default 250, time before auto-complete suggestions show, 5 is instant
completion-trigger-len = 1 # default 2, num of chars before auto-complete shows
# rulers = [90] # column position(s) to show ruler
bufferline = "multiple" # default never, options always and multiple
color-modes = true # default false, colors mode indicator
popup-border = "all"

end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false # show hidden files

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[editor.indent-guides]
render = false
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 3

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
V = ["extend_line_below", "select_mode"]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
esc = ["collapse_selection", "keep_primary_selection"]
# 
# Space mode
[keys.normal.space]
x = ":buffer-close"
C-e = "file_explorer"
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]


# Window mode
[keys.normal.space.w]
x = "wclose"
 
# [L]azy mode
[keys.normal.space.l]
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
 
