# Java config below taken from https://gh.jdoneill.com/2025/01/06/helix-jvm-setup/
[language-server.jdtls]
command = "jdtls"
args = ["-data", "~/.cache/jdtls/workspace"]

[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ".git"]
language-servers = ["jdtls"]  

[[language]]
name = "slint"
auto-format = true
# scope = "source.mylang"
file-types = ["slint"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "slint-lsp format /dev/stdin" }
language-servers = [ "slint-lsp" ]
